In [13]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [14]:
df = pd.read_csv('./러일중 1996~현재 기후(시간단위)/러일중 1996(시간).csv', encoding='euckr')
df

지점      지점명                일시    습도  16 방위 풍향   풍속  강수량    현지기압  \
0       26063  상페테르부르크  1996-01-01 15:00  84.9      24.0  3.0  NaN     NaN   
1       26063  상페테르부르크  1996-01-01 18:00  74.6      24.0  4.0  NaN     NaN   
2       26063  상페테르부르크  1996-01-01 21:00  62.0      23.0  4.0  NaN     NaN   
3       26063  상페테르부르크  1996-01-02 00:00  65.1      25.0  5.0  NaN  1023.2   
4       26063  상페테르부르크  1996-01-02 03:00  69.1      25.0  4.0  NaN     NaN   
...       ...      ...               ...   ...       ...  ...  ...     ...   
356947  59981     시사다오  1996-12-31 09:00  66.8       2.0  2.0  NaN     NaN   
356948  59981     시사다오  1996-12-31 12:00  73.0       4.0  2.0  NaN  1016.6   
356949  59981     시사다오  1996-12-31 15:00  76.7       4.0  1.0  NaN     NaN   
356950  59981     시사다오  1996-12-31 18:00  78.5       4.0  1.0  NaN  1016.2   
356951  59981     시사다오  1996-12-31 21:00  81.4       4.0  2.0  NaN     NaN   

          해면기압  변화량 기압  이슬점 온도    기온  최고 기온  최저 기온  
0       1023.4     0.0    -9.3  -7.2    NaN    NaN  
1       1023.3     0.1   -11.9  -8.2   -5.0    NaN  
2       1024.0     0.7   -15.7  -9.8    NaN    NaN  
3       1024.0     0.0   -15.6 -10.3    NaN    NaN  
4       1024.6     0.6   -14.2  -9.6    NaN    NaN  
...        ...     ...     ...   ...    ...    ...  
356947  1015.2     0.4    18.5  25.1    NaN    NaN  
356948  1017.2     2.0    18.1  23.2    NaN    NaN  
356949  1017.5     0.3    18.2  22.5    NaN    NaN  
356950  1016.8     0.7    17.6  21.5   27.1    NaN  
356951  1016.0     0.8    17.8  21.1    NaN    NaN  

[356952 rows x 14 columns]

In [15]:
# df['일시'] = df['일시'].astype('datetime64')
df['일시'] = df['일시'].apply(lambda x:x.split()[0])

In [16]:
df.head(10)

지점      지점명          일시    습도  16 방위 풍향   풍속  강수량    현지기압    해면기압  \
0  26063  상페테르부르크  1996-01-01  84.9      24.0  3.0  NaN     NaN  1023.4   
1  26063  상페테르부르크  1996-01-01  74.6      24.0  4.0  NaN     NaN  1023.3   
2  26063  상페테르부르크  1996-01-01  62.0      23.0  4.0  NaN     NaN  1024.0   
3  26063  상페테르부르크  1996-01-02  65.1      25.0  5.0  NaN  1023.2  1024.0   
4  26063  상페테르부르크  1996-01-02  69.1      25.0  4.0  NaN     NaN  1024.6   
5  26063  상페테르부르크  1996-01-02  66.4      25.0  5.0  NaN     NaN  1024.6   
6  26063  상페테르부르크  1996-01-02  68.5      23.0  4.0  NaN     NaN  1025.5   
7  26063  상페테르부르크  1996-01-02  66.1      25.0  2.0  NaN  1024.7  1025.5   
8  26063  상페테르부르크  1996-01-02  75.1      24.0  1.0  NaN     NaN  1026.1   
9  26063  상페테르부르크  1996-01-03  85.0       0.0  0.0  NaN  1027.1  1027.9   

   변화량 기압  이슬점 온도    기온  최고 기온  최저 기온  
0     0.0    -9.3  -7.2    NaN    NaN  
1     0.1   -11.9  -8.2   -5.0    NaN  
2     0.7   -15.7  -9.8    NaN    NaN  
3     0.0   -15.6 -10.3    NaN    NaN  
4     0.6   -14.2  -9.6    NaN    NaN  
5     0.0   -14.5  -9.4    NaN  -11.0  
6     0.9   -14.6  -9.9    NaN    NaN  
7     0.0   -13.5  -8.3    NaN    NaN  
8     0.1   -15.9 -12.4   -8.1    NaN  
9     0.5   -14.4 -12.4    NaN    NaN

In [17]:
df['16 방위 풍향'].fillna(99).unique()

array([24., 23., 25.,  0.,  9.,  5.,  8.,  7., 13., 14., 17., 31., 22.,
       27., 26., 29., 35., 34., 28., 32.,  2., 12., 16., 20., 19., 18.,
       21., 15., 10., 33., 36.,  4.,  6.,  1., 11., 30.,  3., 40., 86.,
       70., 99., 37., 48., 85., 50., 69., 39., 79., 90., 60., 47., 64.,
       87., 77., 92., 62., 46., 52., 84., 76., 82., 44., 57., 38., 55.,
       41., 80., 68., 72., 75., 66., 94.])

In [18]:
df['16 방위 풍향'].fillna(99,inplace=True)

In [19]:
df['16 방위 풍향'].unique()

array([24., 23., 25.,  0.,  9.,  5.,  8.,  7., 13., 14., 17., 31., 22.,
       27., 26., 29., 35., 34., 28., 32.,  2., 12., 16., 20., 19., 18.,
       21., 15., 10., 33., 36.,  4.,  6.,  1., 11., 30.,  3., 40., 86.,
       70., 99., 37., 48., 85., 50., 69., 39., 79., 90., 60., 47., 64.,
       87., 77., 92., 62., 46., 52., 84., 76., 82., 44., 57., 38., 55.,
       41., 80., 68., 72., 75., 66., 94.])

In [20]:
df['16 방위 풍향'] = df['16 방위 풍향'].apply(lambda x : 99 if x > 36 else x)

In [21]:
df['16 방위 풍향'].unique()

array([24., 23., 25.,  0.,  9.,  5.,  8.,  7., 13., 14., 17., 31., 22.,
       27., 26., 29., 35., 34., 28., 32.,  2., 12., 16., 20., 19., 18.,
       21., 15., 10., 33., 36.,  4.,  6.,  1., 11., 30.,  3., 99.])

In [22]:
import math
df['x_axis'] = df['16 방위 풍향'].apply(lambda x: math.cos(math.radians(x*10)) if 0<x<37 else x)
df['y_axis'] = df['16 방위 풍향'].apply(lambda x: math.sin(math.radians(x*10)) if 0<x<37 else x)

In [23]:
def wind_direct(s):
    if s.value_counts().head(1).index == 99:
        return 99
    else:
        return s[s.values != 99].mean()
    

tdf = df.groupby(['지점명','일시'])['x_axis', 'y_axis'].agg(wind_direct).reset_index()


In [27]:
df_tt = df.groupby(['지점명', '일시']).agg({'기온':['mean','max','min'], '습도':'mean', 
                                        '풍속':'mean', '강수량':'sum','해면기압':'mean','변화량 기압':'mean', 
                                       '이슬점 온도':'mean'})

# df_tt.columns = ['_'.join(x) for x in df_tt.columns.to_flat_index()]
df_tt.columns = ['평균기온','최고기온','최저기온','습도','풍속','강수량','해면기압','변화량기압','이슬점 온도']
df_city = df_tt.reset_index()

In [28]:
df_city

지점명          일시       평균기온  최고기온  최저기온         습도         풍속  강수량  \
0      가고시마  1996-01-01   3.633333   5.0   2.4  77.733333   8.333333  0.0   
1      가고시마  1996-01-02   9.662500  14.3   5.8  68.412500   5.375000  0.0   
2      가고시마  1996-01-03   9.312500  14.3   4.8  53.712500   9.500000  0.0   
3      가고시마  1996-01-04   5.537500  10.6   0.7  59.712500   8.375000  0.0   
4      가고시마  1996-01-05   7.737500  15.3   3.1  63.600000   7.125000  0.0   
...     ...         ...        ...   ...   ...        ...        ...  ...   
45650  히로시마  1996-07-18  28.960000  32.7  25.7  70.870000  10.800000  0.0   
45651  히로시마  1996-07-19  26.800000  27.1  26.5  88.300000  10.000000  0.0   
45652  히로시마  1996-08-14  27.700000  29.3  26.4  86.611111  16.666667  0.0   
45653  히로시마  1996-08-15  29.600000  29.6  29.6  50.700000   4.000000  0.0   
45654  히로시마  1996-08-16  29.300000  29.3  29.3  63.700000   3.000000  0.0   

              해면기압     변화량기압     이슬점 온도  
0      1020.866667  0.366667   0.100000  
1      1019.675000  1.250000   3.812500  
2      1020.325000  0.912500   0.337500  
3      1023.162500  0.937500  -2.075000  
4      1022.050000  0.987500   0.625000  
...            ...       ...        ...  
45650  1004.890000  1.020000  22.820000  
45651  1002.350000  0.350000  24.700000  
45652   986.677778  7.611111  25.211111  
45653  1007.000000  2.100000  18.300000  
45654  1010.500000  1.000000  21.700000  

[45655 rows x 11 columns]

In [29]:
tmplst = []
for ind in range(len(tdf)):
    if tdf.loc[ind,'x_axis'] == 99:
        tmplst.append(1000)
    else:
        tmplst.append(math.degrees(math.atan(tdf.loc[ind,'x_axis']/tdf.loc[ind,'y_axis'])))
tdf['일일 풍향']=tmplst
tdf

지점명          일시    x_axis    y_axis      일일 풍향
0      가고시마  1996-01-01  0.890581 -0.447340 -63.329563
1      가고시마  1996-01-02  0.719246 -0.573488 -51.433023
2      가고시마  1996-01-03  0.753756 -0.581780 -52.337542
3      가고시마  1996-01-04  0.733837 -0.358024 -63.993200
4      가고시마  1996-01-05  0.858075 -0.244420 -74.100547
...     ...         ...       ...       ...        ...
45650  히로시마  1996-07-18  0.406776  0.788157  27.298764
45651  히로시마  1996-07-19  0.962250  0.257834  75.000000
45652  히로시마  1996-08-14 -0.022906  0.376627  -3.480404
45653  히로시마  1996-08-15  0.500000 -0.866025 -30.000000
45654  히로시마  1996-08-16  0.766044 -0.642788 -50.000000

[45655 rows x 5 columns]

In [13]:
# bins = [i for i in range(10,360,20)]
# labels = [i for i in range(20,360,20)]
# len(labels)
# tdf['일일 풍향'] = pd.cut(tdf['일일 풍향'].apply(lambda x: x+360 if x<0 else x),bins=bins,labels=labels).astype('float').fillna(360)

In [30]:
tdf['일일 풍향'] = tdf['일일 풍향'].apply(lambda x: round(x+360,ndigits=-1) if x<0 else round(x,ndigits=-1)).fillna(0)

In [31]:
tdf

지점명          일시    x_axis    y_axis  일일 풍향
0      가고시마  1996-01-01  0.890581 -0.447340  300.0
1      가고시마  1996-01-02  0.719246 -0.573488  310.0
2      가고시마  1996-01-03  0.753756 -0.581780  310.0
3      가고시마  1996-01-04  0.733837 -0.358024  300.0
4      가고시마  1996-01-05  0.858075 -0.244420  290.0
...     ...         ...       ...       ...    ...
45650  히로시마  1996-07-18  0.406776  0.788157   30.0
45651  히로시마  1996-07-19  0.962250  0.257834   80.0
45652  히로시마  1996-08-14 -0.022906  0.376627  360.0
45653  히로시마  1996-08-15  0.500000 -0.866025  330.0
45654  히로시마  1996-08-16  0.766044 -0.642788  310.0

[45655 rows x 5 columns]

In [16]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45655 entries, 0 to 45654
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   지점명     45655 non-null  object 
 1   일시      45655 non-null  object 
 2   x_axis  45655 non-null  float64
 3   y_axis  45655 non-null  float64
 4   일일 풍향   45655 non-null  float64
dtypes: float64(3), object(2)
memory usage: 1.7+ MB


In [17]:
tdf[tdf['일일 풍향'].isna()]

Empty DataFrame
Columns: [지점명, 일시, x_axis, y_axis, 일일 풍향]
Index: []

In [33]:
df_city = pd.concat([df_city,tdf['일일 풍향']],axis=1)

In [35]:
df_city.columns

Index(['지점명', '일시', '평균기온', '최고기온', '최저기온', '습도', '풍속', '강수량', '해면기압', '변화량기압',
       '이슬점 온도', '일일 풍향'],
      dtype='object')

In [37]:
df_city = df_city[['지점명', '일시', '평균기온', '최고기온', '최저기온', '습도', '일일 풍향','풍속',  '강수량', '해면기압', '변화량기압',
       '이슬점 온도']]
df_city.rename({'일일 풍향':'풍향'},axis = 1,inplace=True)
df_city

지점명          일시       평균기온  최고기온  최저기온         습도     풍향         풍속  \
0      가고시마  1996-01-01   3.633333   5.0   2.4  77.733333  300.0   8.333333   
1      가고시마  1996-01-02   9.662500  14.3   5.8  68.412500  310.0   5.375000   
2      가고시마  1996-01-03   9.312500  14.3   4.8  53.712500  310.0   9.500000   
3      가고시마  1996-01-04   5.537500  10.6   0.7  59.712500  300.0   8.375000   
4      가고시마  1996-01-05   7.737500  15.3   3.1  63.600000  290.0   7.125000   
...     ...         ...        ...   ...   ...        ...    ...        ...   
45650  히로시마  1996-07-18  28.960000  32.7  25.7  70.870000   30.0  10.800000   
45651  히로시마  1996-07-19  26.800000  27.1  26.5  88.300000   80.0  10.000000   
45652  히로시마  1996-08-14  27.700000  29.3  26.4  86.611111  360.0  16.666667   
45653  히로시마  1996-08-15  29.600000  29.6  29.6  50.700000  330.0   4.000000   
45654  히로시마  1996-08-16  29.300000  29.3  29.3  63.700000  310.0   3.000000   

       강수량         해면기압     변화량기압     이슬점 온도  
0      0.0  1020.866667  0.366667   0.100000  
1      0.0  1019.675000  1.250000   3.812500  
2      0.0  1020.325000  0.912500   0.337500  
3      0.0  1023.162500  0.937500  -2.075000  
4      0.0  1022.050000  0.987500   0.625000  
...    ...          ...       ...        ...  
45650  0.0  1004.890000  1.020000  22.820000  
45651  0.0  1002.350000  0.350000  24.700000  
45652  0.0   986.677778  7.611111  25.211111  
45653  0.0  1007.000000  2.100000  18.300000  
45654  0.0  1010.500000  1.000000  21.700000  

[45655 rows x 12 columns]

In [39]:
j_li = ['도쿄','오사카','나고야','삿포로','센다이','니가타','히로시마','다카마쓰','후쿠오카','가고시마','오키나와','난징','베이징','상하이','선양','창춘','텐진','다롄','지난','블라디보스톡']
j_li_n = ['n4','n5','n5','n4','n4','n4','n5','n5','n5','n5','n5','n7','n6','n7','n6','n6','n6','n6','n7','n3']


In [41]:
df_city['군집'] = df_city['지점명'].apply(lambda x : j_li_n[j_li.index(x)] if x in j_li else np.nan)

In [62]:
city = df_city[df_city['군집'].isna()==False]

In [63]:
city

지점명          일시       평균기온  최고기온  최저기온         습도     풍향         풍속  \
0      가고시마  1996-01-01   3.633333   5.0   2.4  77.733333  300.0   8.333333   
1      가고시마  1996-01-02   9.662500  14.3   5.8  68.412500  310.0   5.375000   
2      가고시마  1996-01-03   9.312500  14.3   4.8  53.712500  310.0   9.500000   
3      가고시마  1996-01-04   5.537500  10.6   0.7  59.712500  300.0   8.375000   
4      가고시마  1996-01-05   7.737500  15.3   3.1  63.600000  290.0   7.125000   
...     ...         ...        ...   ...   ...        ...    ...        ...   
45650  히로시마  1996-07-18  28.960000  32.7  25.7  70.870000   30.0  10.800000   
45651  히로시마  1996-07-19  26.800000  27.1  26.5  88.300000   80.0  10.000000   
45652  히로시마  1996-08-14  27.700000  29.3  26.4  86.611111  360.0  16.666667   
45653  히로시마  1996-08-15  29.600000  29.6  29.6  50.700000  330.0   4.000000   
45654  히로시마  1996-08-16  29.300000  29.3  29.3  63.700000  310.0   3.000000   

       강수량         해면기압     변화량기압     이슬점 온도  군집  
0      0.0  1020.866667  0.366667   0.100000  n5  
1      0.0  1019.675000  1.250000   3.812500  n5  
2      0.0  1020.325000  0.912500   0.337500  n5  
3      0.0  1023.162500  0.937500  -2.075000  n5  
4      0.0  1022.050000  0.987500   0.625000  n5  
...    ...          ...       ...        ...  ..  
45650  0.0  1004.890000  1.020000  22.820000  n5  
45651  0.0  1002.350000  0.350000  24.700000  n5  
45652  0.0   986.677778  7.611111  25.211111  n5  
45653  0.0  1007.000000  2.100000  18.300000  n5  
45654  0.0  1010.500000  1.000000  21.700000  n5  

[6208 rows x 13 columns]

In [64]:
city.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6208 entries, 0 to 45654
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   지점명     6208 non-null   object 
 1   일시      6208 non-null   object 
 2   평균기온    6208 non-null   float64
 3   최고기온    6208 non-null   float64
 4   최저기온    6208 non-null   float64
 5   습도      6199 non-null   float64
 6   풍향      6208 non-null   float64
 7   풍속      6208 non-null   float64
 8   강수량     6208 non-null   float64
 9   해면기압    6208 non-null   float64
 10  변화량기압   6208 non-null   float64
 11  이슬점 온도  6208 non-null   float64
 12  군집      6208 non-null   object 
dtypes: float64(10), object(3)
memory usage: 679.0+ KB
