In [2]:
import requests
import pandas as pd
import numpy as np

In [4]:
res = requests.get('https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&start=1405699200&end=9999999999&period=86400')
res.json

<bound method Response.json of <Response [200]>>

In [8]:
df = pd.DataFrame(res.json())
df

date          high           low          open         close  \
0     1424304000    244.000000    225.000000    225.000000    244.000000   
1     1424390400    245.000000    240.250000    240.250118    240.250000   
2     1424476800    245.000000    245.000000    245.000000    245.000000   
3     1424563200    249.000000    235.000000    245.000000    235.000000   
4     1424649600    235.001000    235.000000    235.000002    235.000000   
...          ...           ...           ...           ...           ...   
2584  1647561600  42308.476004  40150.087581  40908.000000  41754.811660   
2585  1647648000  42375.089534  41512.409770  41755.212916  42205.579078   
2586  1647734400  42275.251821  40919.255124  42196.264992  41250.308283   
2587  1647820800  41531.500846  40500.000000  41260.158661  41000.449464   
2588  1647907200  43300.000000  40880.465958  40992.250707  42800.000000   

            volume  quoteVolume  weightedAverage  
0     4.627631e+01     0.193117       239.627778  
1     5.589490e+01     0.230429       242.568479  
2     1.472224e+01     0.060091       245.000000  
3     1.291212e+02     0.539055       239.532608  
4     9.656756e+01     0.410926       235.000062  
...            ...          ...              ...  
2584  9.986990e+06   243.314842     41045.544156  
2585  7.471468e+06   178.279937     41908.630814  
2586  8.375151e+06   201.834517     41495.136669  
2587  9.073900e+06   221.057318     41047.723769  
2588  1.025225e+07   242.276375     42316.323160  

[2589 rows x 8 columns]

In [10]:
# close 값만 따로 value 뽑아낸거... 그 이름 죄송합니다. 
c_val = df['close'].values

In [11]:
# 10일 간의 데이터를 가지고 하루 뒤 예측
window_size = 10 # 10일 간의 데이터 크기 설정

c_val

array([  244.        ,   240.25      ,   245.        , ...,
       41250.30828324, 41000.44946372, 42800.        ])

In [12]:
c_val[0:10] # 10개, 이렇게 한묶음을 특징으로 쓰는거임

array([244.        , 240.25      , 245.        , 235.        ,
       235.        , 239.75      , 237.75      , 238.5       ,
       249.        , 240.00006025])

In [13]:
# 그럼 앞에서부터 10개씩 모아야겠쥬?
c_val[0:10] # 이게 x[0]
c_val[1:11] # x[1]
c_val[2:12] # x[2]
# ...  이런식으로

array([245.        , 235.        , 235.        , 239.75      ,
       237.75      , 238.5       , 249.        , 240.00006025,
       251.        , 269.        ])

In [14]:
# 그래서 이 작업을 for문으로 돌려서 반복작업을 해주려고 하는거고 
for ind in range(len(c_val)):
    print(c_val[ind:ind+window_size])
# 이렇게 하면 에러가 뜨...ㄹ 거라고 생각했는데 안뜨네요..?

[244.         240.25       245.         235.         235.
 239.75       237.75       238.5        249.         240.00006025]
[240.25       245.         235.         235.         239.75
 237.75       238.5        249.         240.00006025 251.        ]
[245.         235.         235.         239.75       237.75
 238.5        249.         240.00006025 251.         269.        ]
[235.         235.         239.75       237.75       238.5
 249.         240.00006025 251.         269.         267.21999999]
[235.         239.75       237.75       238.5        249.
 240.00006025 251.         269.         267.21999999 280.        ]
[239.75       237.75       238.5        249.         240.00006025
 251.         269.         267.21999999 280.         257.00012   ]
[237.75       238.5        249.         240.00006025 251.
 269.         267.21999999 280.         257.00012    260.        ]
[238.5        249.         240.00006025 251.         269.
 267.21999999 280.         257.00012    260.         2

 8185.4764035  8218.         8221.15112094 8178.05451886 7731.55172042]
[7720.         8410.         8173.03501117 7938.00204999 8185.4764035
 8218.         8221.15112094 8178.05451886 7731.55172042 7616.01739137]
[8410.         8173.03501117 7938.00204999 8185.4764035  8218.
 8221.15112094 8178.05451886 7731.55172042 7616.01739137 7536.86137497]
[8173.03501117 7938.00204999 8185.4764035  8218.         8221.15112094
 8178.05451886 7731.55172042 7616.01739137 7536.86137497 7411.21513438]
[7938.00204999 8185.4764035  8218.         8221.15112094 8178.05451886
 7731.55172042 7616.01739137 7536.86137497 7411.21513438 7005.        ]
[8185.4764035  8218.         8221.15112094 8178.05451886 7731.55172042
 7616.01739137 7536.86137497 7411.21513438 7005.         7034.20000001]
[8218.         8221.15112094 8178.05451886 7731.55172042 7616.01739137
 7536.86137497 7411.21513438 7005.         7034.20000001 6928.5       ]
[8221.15112094 8178.05451886 7731.55172042 7616.01739137 7536.86137497
 7411.21

 33628.60730237 34250.27539366]
[31384.85424124 31519.21046422 31777.83949396 30821.16333145
 29787.96176314 32136.39343985 32292.47284885 33628.60730237
 34250.27539366 35374.93627258]
[31519.21046422 31777.83949396 30821.16333145 29787.96176314
 32136.39343985 32292.47284885 33628.60730237 34250.27539366
 35374.93627258 37244.82529797]
[31777.83949396 30821.16333145 29787.96176314 32136.39343985
 32292.47284885 33628.60730237 34250.27539366 35374.93627258
 37244.82529797 39471.47241444]
[30821.16333145 29787.96176314 32136.39343985 32292.47284885
 33628.60730237 34250.27539366 35374.93627258 37244.82529797
 39471.47241444 39999.52655611]
[29787.96176314 32136.39343985 32292.47284885 33628.60730237
 34250.27539366 35374.93627258 37244.82529797 39471.47241444
 39999.52655611 40016.        ]
[32136.39343985 32292.47284885 33628.60730237 34250.27539366
 35374.93627258 37244.82529797 39471.47241444 39999.52655611
 40016.         42183.51940453]
[32292.47284885 33628.60730237 34250.2753936

In [17]:
# 마지막 부분을 보시면 원소가 하나만 들어갔어요. 네 없어서 안들어간겁니다. 
# 이게 사실 지혜누나가 헷갈리는 부분이었는데 
# 앞에서 부터 없어지는거다 아니다 뒤에꺼 없애는거다가 중요하지 않다고 말한게 앞에서부터 없애면 앞에서부터 없애는거고 뒤에서부터 없애면 뒤에서부터 없애는거라...
# 뭔말인지 나도 몰라요 암튼 
# 뒤에서부터 10번째까지는 10개씩 잘들어가요
len(c_val[-10:])

10

In [18]:
# 근디 9번째부터는 다 안들어가요
len(c_val[-9:])

9

In [19]:
#그래서 얘는 불완전한 데이터가 되는거라 버려야해요
# 그러면 window size크기 만큼 뒤에 있는 값은 가져갈수 있는거니깐
for ind in range(len(c_val)-window_size):
    print(c_val[ind:ind+window_size])
# 이렇게 해주면 마지막 값이 10개로 온전한 데이터가 되겠쥬?
len(c_val[ind:ind+window_size]) # 10이라고 나옵니다

[244.         240.25       245.         235.         235.
 239.75       237.75       238.5        249.         240.00006025]
[240.25       245.         235.         235.         239.75
 237.75       238.5        249.         240.00006025 251.        ]
[245.         235.         235.         239.75       237.75
 238.5        249.         240.00006025 251.         269.        ]
[235.         235.         239.75       237.75       238.5
 249.         240.00006025 251.         269.         267.21999999]
[235.         239.75       237.75       238.5        249.
 240.00006025 251.         269.         267.21999999 280.        ]
[239.75       237.75       238.5        249.         240.00006025
 251.         269.         267.21999999 280.         257.00012   ]
[237.75       238.5        249.         240.00006025 251.
 269.         267.21999999 280.         257.00012    260.        ]
[238.5        249.         240.00006025 251.         269.
 267.21999999 280.         257.00012    260.         2

 6164.34251788 6151.81429999 6240.00000166 6078.39999986 6137.87057885]
[6746.         6753.         6712.63276587 6041.6665     6164.34251788
 6151.81429999 6240.00000166 6078.39999986 6137.87057885 5872.99999926]
[6753.         6712.63276587 6041.6665     6164.34251788 6151.81429999
 6240.00000166 6078.39999986 6137.87057885 5872.99999926 6197.50000071]
[6712.63276587 6041.6665     6164.34251788 6151.81429999 6240.00000166
 6078.39999986 6137.87057885 5872.99999926 6197.50000071 6390.5236881 ]
[6041.6665     6164.34251788 6151.81429999 6240.00000166 6078.39999986
 6137.87057885 5872.99999926 6197.50000071 6390.5236881  6348.80000001]
[6164.34251788 6151.81429999 6240.00000166 6078.39999986 6137.87057885
 5872.99999926 6197.50000071 6390.5236881  6348.80000001 6614.23108202]
[6151.81429999 6240.00000166 6078.39999986 6137.87057885 5872.99999926
 6197.50000071 6390.5236881  6348.80000001 6614.23108202 6497.65940927]
[6240.00000166 6078.39999986 6137.87057885 5872.99999926 6197.50000071

 34670.16896056 35298.76490713]
[32274.1788612  34650.55903888 34460.17487883 35901.87903287
 35036.69606858 33529.99068841 33788.57151371 34670.16896056
 35298.76490713 33684.95802664]
[34650.55903888 34460.17487883 35901.87903287 35036.69606858
 33529.99068841 33788.57151371 34670.16896056 35298.76490713
 33684.95802664 34228.44762482]
[34460.17487883 35901.87903287 35036.69606858 33529.99068841
 33788.57151371 34670.16896056 35298.76490713 33684.95802664
 34228.44762482 33863.2693    ]
[35901.87903287 35036.69606858 33529.99068841 33788.57151371
 34670.16896056 35298.76490713 33684.95802664 34228.44762482
 33863.2693     32856.36198235]
[35036.69606858 33529.99068841 33788.57151371 34670.16896056
 35298.76490713 33684.95802664 34228.44762482 33863.2693
 32856.36198235 33834.27391324]
[33529.99068841 33788.57151371 34670.16896056 35298.76490713
 33684.95802664 34228.44762482 33863.2693     32856.36198235
 33834.27391324 33503.84953936]
[33788.57151371 34670.16896056 35298.76490713 33

10

In [27]:
# 그래서 이걸 활용해서 x 데이터를 만들면 되는거지 
x = []
for ind in range(len(c_val)-window_size):
    x.append(c_val[ind:ind+window_size])

In [29]:
# 그래서 여기선 x가 가져갈 범위를 1 더줄여줘야 마지막 y값까지 온전하게 가져갈 수 있답니다
x = []
y = []
for ind in range(len(c_val)-window_size):
    x.append(c_val[ind:ind+window_size])
    y.append(c_val[ind+window_size])
print(len(x),len(y))

2579 2579


In [ ]:
# 어라라 왜 2578이지 2579 아녔나?
# 암튼 난 맞게함 틀렸으면 강사님이 틀렸겠..지?